### ISSUE TITLE
Looks like older versions of git is having issues with tags?

### ISSUE THREAD

**Issue by itamblyn** [hashkat/hashkat#29]
./run.sh -O --build
fatal: No annotated tags can describe 'cdc30b1cb4ecda86d393d6c92b2297655c4fb3f7'.
However, there were unannotated tags: try --tags.

**Comment by ludamad** [comment]
Everything tag related should work now that there are actual tags

**Comment by itamblyn** [comment]
I still get this on build on a P7 with an older version of git. It looks like it's just a warning: 

p7n01-$ ./run.sh -O --build
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=nr
    --max-age=epoch
    --min-age=epoch
    --sparse
    --no-merges
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=nr | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all

Other issues about this are no longer happening so let's leave this closed
